# proxy = ""
# editor = ""
# vscroot = ""
# vscwroot = ""

# [git.auths]
# <username> = "<email>"

# [ssh.auths]
# name = "<username>@<host>"

# [ssh.ports]
# name = <port>

# [s3.<name>]
# name = "<bucketname>"
# ak = "<accesskey>"
# sk = "<secretkey>"
# region = "<region>"
# endpoint = "<endpoint>"
