version: '3.1'

networks:
    dev:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 10.7.0.0/24
                  gateway: 10.7.0.1

services:
    redisdb:
        container_name: redisdb
        image: redis
        ports:
            - "127.0.0.1:6379:6379"
        networks:
            dev:
                ipv4_address: 10.7.0.2

    mongodb:
        container_name: mongodb
        image: mongo
        ports:
            - "127.0.0.1:27017:27017"
        environment:
            - MONGO_INITDB_ROOT_USERNAME=root
            - MONGO_INITDB_ROOT_PASSWORD=123456
        networks:
            dev:
                ipv4_address: 10.7.0.3

    ws:
        container_name: ws
        build:
            dockerfile: dev.ws.dockerfile
        ports:
            - "127.0.0.1:9080:80"
            - "127.0.0.1:5432:5432"
            - "127.0.0.1:5433:5433"
        networks:
            dev:
                ipv4_address: 10.7.0.4
